services:
  db-web:
    image: mysql:8.4
    ports:
      - 3306:3306
    networks:
      - mi-conexion
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=web
  website:
    image: nginx:stable-alpine-perl
    ports:
      - 8088:80
    build:
      dockerfile: Dockerfile

networks:
  mi-conexion:
    driver: bridge
volumes:
  mysql-data:
    external: false